name: CI Process

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']
env:
  NEXT_PUBLIC_API_URL: 'https://api.minzifatravel.com'
  NEXT_PUBLIC_ARTICLES_API_URL: 'https://articles.minzifatravel.com'

  NEXT_PUBLIC_CENTRIFUGE_URL: 'wss://centrifugo.minzifatravel.com/connection/websocket'
  NEXT_PUBLIC_GOOGLE_CAPTCHA_KEY: '6LdlmvUrAAAAANvBU2OVEgyM7bHRwLCb-39VU5-z'
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: '318070515673-49vkq4lf8g8cn7dktg00md7ap5ms5v33.apps.googleusercontent.com'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - run: npm install
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm run start
